AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  PostgreSQLUsername:
    Type: String
  PostgreSQLPassword:
    Type: String
  PostgreSQLHost:
    Type: String
  PostgreSQLPort:
    Type: Number
  PostgreSQLDBName:
    Type: String
  StageName:
    Type: String
  EnvironmentName:
    Type: String
  Auth0Domain:
    Type: String
  Auth0Audience:
    Type: String
  AppsyncCoreApiUrl:
    Type: String
  AppsyncCoreApiKey:
    Type: String
  FacebookMessengerBotVerifyToken:
    Type: String
  DatabasesLayerARN:
    Type: String
  RequestsLayerARN:
    Type: String
  SciPyLayerARN:
    Type: String
    Default: 'arn:aws:lambda:eu-central-1:292169987271:layer:AWSLambda-Python38-SciPy1x:29'
  OpenCVLayerARN:
    Type: String
  FileStorageServiceUrl:
    Type: String
Globals:
  Function:
    Runtime: python3.8
    MemorySize: 10240
    Timeout: 900
    Environment:
      Variables:
        POSTGRESQL_USERNAME:
          'Fn::Sub': '${PostgreSQLUsername}'
        POSTGRESQL_PASSWORD:
          'Fn::Sub': '${PostgreSQLPassword}'
        POSTGRESQL_HOST:
          'Fn::Sub': '${PostgreSQLHost}'
        POSTGRESQL_PORT:
          'Fn::Sub': '${PostgreSQLPort}'
        POSTGRESQL_DB_NAME:
          'Fn::Sub': '${PostgreSQLDBName}'
        APPSYNC_CORE_API_URL:
          'Fn::Sub': '${AppsyncCoreApiUrl}'
        APPSYNC_CORE_API_KEY:
          'Fn::Sub': '${AppsyncCoreApiKey}'
        FILE_STORAGE_SERVICE_URL:
          'Fn::Sub': '${FileStorageServiceUrl}'
Resources:
  FacebookMessengerApiGateway:
    Type: 'AWS::Serverless::HttpApi'
    Properties:
      StageName:
        'Fn::Sub': '${StageName}'
      CorsConfiguration:
        AllowMethods:
          - GET
          - POST
        AllowHeaders:
          - '*'
        AllowOrigins:
          - '*'
      Auth:
        Authorizers:
          Auth0Authorizer:
            JwtConfiguration:
              issuer:
                'Fn::Sub': '${Auth0Domain}'
              audience:
                - 'Fn::Sub': '${Auth0Audience}'
            IdentitySource: $request.header.Authorization
  SendMessageFromFacebookMessenger:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName:
        'Fn::Sub': '${EnvironmentName}SendMessageFromFacebookMessenger'
      CodeUri: src/aws_lambda_functions/send_message_from_facebook_messenger
      Handler: lambda_function.lambda_handler
      Events:
        FacebookMessengerApiGatewayGetRequest:
          Type: HttpApi
          Properties:
            ApiId:
              Ref: FacebookMessengerApiGateway
            Path: '/'
            Method: GET
        FacebookMessengerApiGatewayPostRequest:
          Type: HttpApi
          Properties:
            ApiId:
              Ref: FacebookMessengerApiGateway
            Path: '/'
            Method: POST
      Environment:
        Variables:
          FACEBOOK_MESSENGER_BOT_VERIFY_TOKEN:
            'Fn::Sub': '${FacebookMessengerBotVerifyToken}'
      Layers:
        - 'Fn::Sub': '${DatabasesLayerARN}'
        - 'Fn::Sub': '${RequestsLayerARN}'
        - 'Fn::Sub': '${OpenCVLayerARN}'
        - 'Fn::Sub': '${SciPyLayerARN}'
  SendMessageToFacebookMessenger:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName:
        'Fn::Sub': '${EnvironmentName}SendMessageToFacebookMessenger'
      CodeUri: src/aws_lambda_functions/send_message_to_facebook_messenger
      Handler: lambda_function.lambda_handler
      Events:
        FacebookMessengerApiGateway:
          Type: HttpApi
          Properties:
            ApiId:
              Ref: FacebookMessengerApiGateway
            Path: /send_message_to_facebook_messenger
            Method: POST
            Auth:
              Authorizer: Auth0Authorizer
      Layers:
        - 'Fn::Sub': '${DatabasesLayerARN}'
        - 'Fn::Sub': '${RequestsLayerARN}'
  SendNotificationToFacebookMessenger:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName:
        'Fn::Sub': '${EnvironmentName}SendNotificationToFacebookMessenger'
      CodeUri: src/aws_lambda_functions/send_notification_to_facebook_messenger
      Handler: lambda_function.lambda_handler
      Events:
        FacebookMessengerApiGateway:
          Type: HttpApi
          Properties:
            ApiId:
              Ref: FacebookMessengerApiGateway
            Path: /send_notification_to_facebook_messenger
            Method: POST
            Auth:
              Authorizer: Auth0Authorizer
      Layers:
        - 'Fn::Sub': '${DatabasesLayerARN}'
        - 'Fn::Sub': '${RequestsLayerARN}'
  SendTemplateToFacebookMessenger:
      Type: AWS::Serverless::Function
      Properties:
          FunctionName:
              Fn::Sub: "${EnvironmentName}SendTemplateToFacebookMessenger"
          CodeUri: src/aws_lambda_functions/send_template_to_facebook_messenger
          Handler: lambda_function.lambda_handler
          Events:
              FacebookMessengerApiGatewayEvent:
                  Type: HttpApi
                  Properties:
                      ApiId:
                          Ref: FacebookMessengerApiGateway
                      Path: /send_template_to_facebook_messenger
                      Method: POST
                      Auth:
                          Authorizer: Auth0Authorizer
          Layers:
              - Fn::Sub: "${DatabasesLayerARN}"
              - Fn::Sub: "${RequestsLayerARN}"
